# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages
before_install:
  - git config --global user.name "Travis CI"
  - git config --global user.email "user@example.com"
after_success:
  - Rscript -e 'covr::coveralls()'
